[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
  "/dist",
  "/notebooks",
  "/scripts",
  "/bin",
  "/tests"
]
[project]
name = "openeo_gfmap"
version = "0.0.1"
authors = [
  { name="Darius Couchard" },
  { name="Vincent Verelst" },
  { name="Kristof Van Tricht" },
  { name="Stefaan Lippens" },
  { name="Jeroen Degerickx" }
]
description = "OpenEO General Framework for Mapping"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "openeo",
    "xarray",
    "rioxarray",
    "hydra-core",
    "geojson",
]