project:
  type: website
output-dir: ../docs
resources:
  - "data/**"
navbar:
  title: "GFMAP"
  right:
    - text: "Introduction"
      href: introduction.qmd
    - text: "Sections"
      dropdown:
        - text: "Data Fetching"
          href: fetching.qmd
        - text: "Preprocessing"
          href: preprocessing.qmd
        - text: "Features"
          href: features.qmd
        - text: "Inference"
          href: inference.qmd
        - text: "Managers"
          href: managers.qmd
        - text: "Utils"
          href: utilities.qmd
  